/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProxiesRouteImport } from './routes/proxies'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as TimeSlotsRouteImport } from './routes/time-slots'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxiesRoute = ProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeSlotsRoute = TimeSlotsRouteImport.update({
  id: '/time-slots',
  path: '/time-slots',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/proxies': typeof ProxiesRoute
  '/strategies': typeof StrategiesRoute
  '/time-slots': typeof TimeSlotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/proxies': typeof ProxiesRoute
  '/strategies': typeof StrategiesRoute
  '/time-slots': typeof TimeSlotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/proxies': typeof ProxiesRoute
  '/strategies': typeof StrategiesRoute
  '/time-slots': typeof TimeSlotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/history'
    | '/login'
    | '/proxies'
    | '/strategies'
    | '/time-slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/history'
    | '/login'
    | '/proxies'
    | '/strategies'
    | '/time-slots'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/history'
    | '/login'
    | '/proxies'
    | '/strategies'
    | '/time-slots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRoute: typeof BotsRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProxiesRoute: typeof ProxiesRoute
  StrategiesRoute: typeof StrategiesRoute
  TimeSlotsRoute: typeof TimeSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxies': {
      id: '/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof ProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-slots': {
      id: '/time-slots'
      path: '/time-slots'
      fullPath: '/time-slots'
      preLoaderRoute: typeof TimeSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRoute: BotsRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProxiesRoute: ProxiesRoute,
  StrategiesRoute: StrategiesRoute,
  TimeSlotsRoute: TimeSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
